Kirilushkin Aleksandr Task 1
KirilushkinAleksandr/ui-internship-markup pull request #1
Opened 2019-09-27 14:55 UTC by KirilushkinAleksandr

2019-10-14 07:48 UTC, alexkond requested changes

2019-10-14 07:48 UTC, alexkond commented on task-1/public/index.html
> +      <span class="content-block__title">about us</span>
You have `.content-block` element inside `.wrapper` block, that' breaking of BEM basic principle. You could have block inside element but not element of one block inside another block. It means you can't use your `.content-block` block with its elements without `.wrapper` block.

2019-10-14 07:48 UTC, alexkond commented on task-1/public/index.html
> +      <span class="tile__name content-block__title">
You're using elements outside its block. That breaks the basic BEM principle.

2019-10-14 07:48 UTC, alexkond commented on task-1/public/index.html
> +    <div class="footer-info wrapper">
Two blocks on the same element don't look right.

2019-10-14 07:48 UTC, alexkond commented on task-1/public/styles/style.css
> +  top: 18%;
Does this block will always be moved 18% down anywhere it will be placed?

2019-10-14 07:48 UTC, alexkond commented on task-1/public/styles/style.css
> +  margin: 20px 18%;
margin in percents is a bad practice

2019-10-15 05:54 UTC, alexkond submitted a review, later dismissed

2019-10-15 08:27 UTC, vadeneev approved these changes

2019-10-15 08:38 UTC, alexkond approved these changes

2019-10-15 08:38 UTC, merged