Kirilushkin Aleksandr Task 2
KirilushkinAleksandr/ui-internship-markup pull request #2
Opened 2019-10-09 15:47 UTC by KirilushkinAleksandr

https://aleksandr-kirilushkin-task2.firebaseapp.com/

2019-10-10 06:00 UTC, alexkond requested changes

2019-10-10 06:00 UTC, alexkond commented on task-2/public/index.html
> +        </form>
Please add the required attributes for form, inputs and label.

2019-10-10 06:00 UTC, alexkond commented on task-2/public/index.html
> +        <a class="article__link" href="#">leave a comment</a>
Do you think this link could be used outside of the article?

2019-10-10 06:00 UTC, alexkond commented on task-2/public/index.html
> +        </div>
Don't you think this social block could be used outside of the footer?

2019-10-10 06:00 UTC, alexkond commented on task-2/public/index.html
> +        </div>
Does it looks like `<nav>`?

2019-10-10 06:00 UTC, alexkond commented on task-2/public/styles/scss/blocks/article.scss
> +      margin-bottom: 10%;
It's not recommended to use percents for margin.

2019-10-10 06:00 UTC, alexkond commented on task-2/public/styles/scss/blocks/article.scss
> +    font-weight: 300;
Please use mixins for font-related stuff.

2019-10-10 06:00 UTC, alexkond commented on task-2/public/styles/scss/blocks/article.scss
> +    line-height: 24px;
It looks like a good candidate for the mixin.

2019-10-10 06:00 UTC, alexkond commented on task-2/public/styles/scss/blocks/header.scss
> +    line-height: 24px;
Another one font-related rule that could be converted to the mixin.

2019-10-10 06:00 UTC, alexkond commented on task-2/public/styles/scss/blocks/sign-up-box.scss
> +  margin:auto -163px auto -164px;
Could it be `margin: auto -164px;`?

2019-10-14 08:15 UTC, alexkond requested changes

2019-10-14 08:15 UTC, alexkond commented on task-2/public/index.html
> +        <button class="button_load">
Could these styles be used only for the button that loads more content?

2019-10-14 08:15 UTC, alexkond commented on task-2/public/index.html
> +          <a class="button_link social__links_icon social__links_icon-facebook " href="#">
Should it really look like a link? Don't think that this is a good place for the `button-link` class.

2019-10-14 08:15 UTC, alexkond commented on task-2/public/styles/scss/blocks/article.scss
> +  margin-bottom: 100px;
Blocks should not affect its outer space.

2019-10-14 08:15 UTC, alexkond commented on task-2/public/styles/scss/blocks/button.scss
> +    align-self: center;
Why button should align itself? What if you'll need the same button but positioned left or right?

2019-10-14 08:15 UTC, alexkond commented on task-2/public/styles/scss/blocks/button.scss
> +    margin-bottom: 100px;
Your button adds 100px of empty space after it and affects its outer space.

2019-10-14 08:15 UTC, alexkond commented on task-2/public/styles/scss/variables/mixins.scss
> +@mixin header-logo {
Most of your mixins are adding some text styling but its names are confusing because you can't see its purpose from its names.

2019-10-17 06:59 UTC, alexkond approved these changes

2019-10-30 06:51 UTC, vovcyan approved these changes

2019-10-30 07:09 UTC, merged